version: 2
updates:
  # Enable version updates for maven
  - package-ecosystem: "maven"
    # Look for `pom.xml` in the `root` directory
    directory: "/"
    open-pull-requests-limit: 10
    # Check for updates once daily
    schedule:
      interval: "daily"
    commit-message:
      # Conventional Commit prefix
      prefix: "deps(java)"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
    commit-message:
      # Conventional Commit prefix
      prefix: "deps(CI)"