name: Maintain Unreleased Changes

on:
  push:
    branches:
      - main
  workflow_call:

jobs:
  unreleased_changes:
    name: Maintain Unreleased Changes
    runs-on: ubuntu-latest

    # Prevents merge conflicts by cancelling duplicate executions of this job
    concurrency: unreleased_changes

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the added or changed files to the repository
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          # Enables compiling the changelog when creating the new release by fetching the commit-history
          fetch-depth: 0
          # Improves efficiency of this action by only downloading necessary data (see filter option of git clone)
          filter: tree:0

      # Ensures that no unreleased changes are missed when multiple instances of this workflow are triggered at the same time
      - name: Pull latest changes
        env:
          USERNAME: 'Pull_Action_User'
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git pull origin main -r -X theirs

      - name: Create log file with unreleased changes
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: .github/workflows/config/cliff.toml
          args: -v --unreleased --strip header
        env:
          OUTPUT: UNRELEASED_CHANGES.md

      - name: Commit UNRELEASED_CHANGES.md
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: 'chore(doc): maintain UNRELEASED_CHANGES.md'
          file_pattern: UNRELEASED_CHANGES.md